/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-02-21 05:11:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.html", Long.valueOf(1487652938000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    ");
      amlyp.companyDB.User customer = null;
      synchronized (session) {
        customer = (amlyp.companyDB.User) _jspx_page_context.getAttribute("customer", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (customer == null){
          customer = new amlyp.companyDB.User();
          _jspx_page_context.setAttribute("customer", customer, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write(" \n");
      out.write("    ");
      amlyp.companyDB.Items item = null;
      synchronized (session) {
        item = (amlyp.companyDB.Items) _jspx_page_context.getAttribute("item", javax.servlet.jsp.PageContext.SESSION_SCOPE);
        if (item == null){
          item = new amlyp.companyDB.Items();
          _jspx_page_context.setAttribute("item", item, javax.servlet.jsp.PageContext.SESSION_SCOPE);
        }
      }
      out.write(' ');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("item"), request);
      out.write(' ');
      out.write('\n');
      out.write('	');
if(!customer.getLoggedIn()){response.sendRedirect("Login.jsp");
} 
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Script/jquery.js\"></script>\n");
      out.write("<script language=\"javascript\" type=\"text/javascript\" src=\"Script/script.js\"></script>\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class = \"search\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <table  border=\"0\">\r\n");
      out.write("\r\n");
      out.write("   <tr>\r\n");
      out.write("           <form method=\"post\" action = \"SearchResult.jsp\">\r\n");
      out.write("   \r\n");
      out.write(" <td><input class = \"search-box\" type=\"text\" name=\"Search\" size=\"30\" maxlength=\"50\">\r\n");
      out.write("\r\n");
      out.write("        <td>\r\n");
      out.write("       <input style = \"color: blue; background-color: lightblue;\" type=\"submit\" value=\"Search\"></td><td>\r\n");
      out.write("       </form>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("        <a href=\"AdvancedSearch.jsp\"><input style = \" color: blue; \"type=\"button\" value=\"Advanced Search\"></a>\r\n");
      out.write("\r\n");
      out.write("     </td>\r\n");
      out.write("   </tr>\r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"menu-wrap\">\r\n");
      out.write("  <nav class=\"menu\">\r\n");
      out.write("    <ul class=\"clearfix\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <li><a href=\"Profile.jsp\">Profile</li></a>\r\n");
      out.write("      <li class = \"menuLable\"> Buy\r\n");
      out.write("        <ul class=\"sub-menu\">\r\n");
      out.write("          <li><a href=\"listitemsbidon.jsp\">Bidding Status</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class = \"menuLable\">Sell\r\n");
      out.write("        <ul class=\"sub-menu\">\r\n");
      out.write("          <li><a href=\"viewMyItems.jsp\">My Items</a></li>\r\n");
      out.write("          <li><a href=\"additem.jsp\">Add New Items</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("        <li class = \"menuLable\">Feedback\r\n");
      out.write("        <ul class=\"sub-menu\">\r\n");
      out.write("          <li><a href=\"leavefeedback.jsp\">Leave Feedback</a></li>\r\n");
      out.write("          <li><a href=\"viewmyfeedback.jsp\">View my Feedback</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"Logout.jsp\">Log Out</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <li><a href = \"userwelcome.jsp\" ><img  class = \"logo\" src=\"Images/logo.png\" ></a></li>\r\n");
      out.write("\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"CSS/style.css\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("<h1>Bid on Item</h1>\n");
      out.write("<table>\n");
      out.write("\n");
      out.write("<tr><td>Item Id</td><td><input disabled name = \"itemId\" value = \"");
      out.print(item.getItemId());
      out.write("\"></td><td></tr>\n");
      out.write("<tr><td>Item Name</td><td><input disabled value = \"");
      out.print(item.getItemName());
      out.write("\"></td><td></tr>\n");
      out.write("\n");
      out.write("<tr><td>Current Winning Bid</td><td><input disabled value = \"");
      out.print("$" + String.format("%.2f", item.findCurrentWinning(item.getItemId())));
      out.write("\"></td><td></tr>\n");
      out.write("<form method = \"post\" action = \"Bid_Action.jsp\">\n");
      out.write("<tr><td>Max Bid Limit</td><td><input name = \"bid\"></td><td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("<tr><td><input style = \"color: blue ; \"type = \"submit\" value = \"Bid On Item\" > <input style = \"color:blue;\"\" type = \"reset\" value = \"Cancel\"></td></tr></form>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
